name: Client

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup client Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '14.x'
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/client/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm install
        working-directory: client

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          build_directory: ~/client/.npm
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true