name: Client

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup client Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '14.x'
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/client/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm install && npm run build --if-present
        working-directory: ./client

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    name: 'Deploy to Netlify'
    steps:
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: '../client'
        env:  
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}